server:
  port: 10100
spring:
  application:
    name: infra-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: api
    sentinel:
      datasource:
        type: nacos
        nacos:
          address: localhost:8848
          username: nacos
          password: nacos
          namespace: sentinel
          data-id: ${spring.application.name}-flow-rules
          group-id: ${spring.application.name}
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: sample_route
          uri: lb://sample
          predicates:
            - Path=/sample/**
          filters:
            - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /management
  endpoint:
    health:
      show-details: "always"
      enabled: false
  server:
    port: 10101
logging:
  level:
    root: INFO