spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: api
    sentinel:
      datasource:
        type: nacos
        nacos:
          address: localhost:8848
          username: nacos
          password: nacos
          namespace: sentinel
          data-id: ${spring.application.name}-flow-rules
          group-id: ${spring.application.name}
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      metrics:
        enabled: true # 启用 Gateway Metrics
      routes:
        - id: sample-route
          uri: lb://sample
          predicates:
            - Path=/sample/**
          filters:
            - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有端点
      base-path: /management
  metrics:
    export:
      prometheus:
        enabled: true # 启用 Prometheus 指标导出
  endpoint:
    health:
      show-details: "always"
      enabled: false
  server:
    port: 10101
logging:
  level:
    root: INFO